"""Codebook construction: noiseless hypothesis rows over a CFO grid, plus optional
don't-care (ternary) masking of decision-boundary bits.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .tx import tx_waveform, STANDARD_ACCESS_ADDRESS
from .channel import apply_cfo
from .encode import differential_product, rotated_axes, CODES, code_width, assemble_key


@dataclass
class Codebook:
    rows: np.ndarray          # (N, W) bool
    df_grid: np.ndarray       # (N,) Hz, hypothesis CFO for each row
    mask: np.ndarray | None   # (N, W) bool, True = don't-care, or None
    W: int
    N: int
    delta: float
    tau: int | None = None


def cfo_grid(df_min: float, df_max: float, delta: float) -> np.ndarray:
    n = int(np.floor((df_max - df_min) / delta)) + 1
    return df_min + delta * np.arange(n)


def _projection_magnitudes(z: np.ndarray, B: int) -> np.ndarray:
    u = rotated_axes(B)
    return np.abs(np.real(z[:, None] * np.conj(u)[None, :]))


def build_codebook(N: int | None = None, delta: float | None = None,
                    df_min: float = -150e3, df_max: float = 150e3,
                    n_sym: int = 40, osr: int = 4, B: int = 2,
                    coding: str = "thermometer",
                    access_address: int = STANDARD_ACCESS_ADDRESS,
                    dont_care_frac: float = 0.0,
                    diff_delay: int = 1) -> Codebook:
    """Build N (or as many as fit df_min..df_max at spacing delta) hypothesis rows.

    Each row is generated by passing the noiseless TX waveform through the same
    encoding chain at hypothesis CFO df_k, with theta0=0 and zero timing offset,
    exactly as the real front end would (no shortcuts through angle()).
    """
    if delta is None:
        if N is None:
            raise ValueError("must supply either N or delta")
        delta = (df_max - df_min) / max(N - 1, 1)
    grid = cfo_grid(df_min, df_max, delta)
    if N is not None:
        grid = grid[:N]
    N_actual = len(grid)

    tx = tx_waveform(n_sym=n_sym, osr=osr, access_address=access_address)
    code_fn = CODES[coding]
    cw = code_width(B, coding)
    n_z = n_sym * osr - diff_delay
    W = n_z * cw

    rows = np.zeros((N_actual, W), dtype=bool)
    mask = np.zeros((N_actual, W), dtype=bool) if dont_care_frac > 0 else None

    for k, df in enumerate(grid):
        sig = apply_cfo(tx, df, osr)
        z = differential_product(sig, delay=diff_delay)
        bits_2d = code_fn(z, B)
        rows[k] = assemble_key(bits_2d).astype(bool)
        if dont_care_frac > 0:
            mag = _projection_magnitudes(z, B).reshape(-1)
            thresh = np.percentile(mag, dont_care_frac * 100)
            mask[k] = mag <= thresh

    return Codebook(rows=rows, df_grid=grid, mask=mask, W=W, N=N_actual, delta=delta)


def capture_window_half_width(df_grid: np.ndarray, rows: np.ndarray, tau: int,
                               center_idx: int, tx_row: np.ndarray | None = None) -> float:
    """Empirically measure Wc: the half-width (Hz) of the contiguous band of rows
    within tau Hamming distance of the row at center_idx (used as a noiseless
    reference 'received key' stand-in). Returns Hz.
    """
    ref = rows[center_idx] if tx_row is None else tx_row
    dist = (rows != ref[None, :]).sum(axis=1)
    within = dist <= tau
    if not within[center_idx]:
        return 0.0
    # walk outward from center to find contiguous extent
    lo = center_idx
    while lo - 1 >= 0 and within[lo - 1]:
        lo -= 1
    hi = center_idx
    while hi + 1 < len(within) and within[hi + 1]:
        hi += 1
    half_width = (df_grid[hi] - df_grid[lo]) / 2.0
    return half_width
